source $HOME/AppData/Local/nvim/general/settings.vim
source $HOME/AppData/Local/nvim/keys/mappings.vim
source $HOME/AppData/Local/nvim/vim-plug/plugins.vim
source $HOME/AppData/Local/nvim/themes/papercolor.vim
source $HOME/AppData/Local/nvim/themes/airline.vim
source $HOME/AppData/Local/nvim/plug-config/coc.vim 
source $HOME/AppData/Local/nvim/plug-config/sneak.vim
source $HOME/AppData/Local/nvim/keys/which-key.vim
source $HOME/AppData/Local/nvim/plug-config/floaterm.vim
source $HOME/AppData/Local/nvim/plug-config/quickscope.vim
